# Generated by Django 4.0.5 on 2023-03-11 15:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_id', models.CharField(max_length=26, unique=True)),
                ('referal_lvl', models.IntegerField(default=1)),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('bonus_deposit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('affected_parents_deposit', models.BooleanField(default=False, editable=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.referalusermodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
