# Generated by Django 4.0.5 on 2023-03-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referalusermodel',
            name='referal_id',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
