# Generated by Django 4.0.5 on 2023-03-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_referalusermodel_referal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="referalusermodel",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited",
                to="users.referalusermodel",
            ),
        ),
        migrations.AddField(
            model_name="referalusermodel",
            name="referal_lvl",
            field=models.IntegerField(default=1),
        ),
    ]
